# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68cc9ce35bae5b334d64c62c9c9c3d41b65c37f37ad1d33407629cbe44c2a5819ed29d0ed4ab0c358ddb7d8a5b8f6eb872b8aec911cdb8a71cbd93688fdbf5f5

test:
  secret_key_base: ef1992d2b6e5f5dd81412ae70f14e04e7001804b0f3420d6068e18ac1b7895940dce862517602800762ae7010bfef51aa13d24a5fc36f6c0fb821054d6bc6d3c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
